import type { Metadata } from "next";
import "./globals.css";
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link href="https://api.fontshare.com/v2/css?f[]=cabinet-grotesk@800&display=swap" rel="stylesheet"></link>
        <link href="https://api.fontshare.com/v2/css?f[]=supreme@500&display=swap" rel="stylesheet"></link>
        <link href="https://api.fontshare.com/v2/css?f[]=bespoke-sans@700&display=swap" rel="stylesheet"></link>
      </head>
      <body className={inter.className}>
        {children}
      </body>
    </html>
  );
}
